### ISSUE TITLE
Review comments on gRPC Guide

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/guide-grpc-intro#10] opened 2022-09-05 11:05 UTC
As per commit 5aa254e07abdc6e5260574986907202e45a83136 (HEAD -> draft, origin/draft, origin/HEAD)

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#what-is-grpc

In "For each service defined in a .proto file, gRPC uses it to generate the skeleton code for users to implement and extend. "
"it" would be better as "the definition"

"much faster" -> "faster"

"either supported languates" -> other supported languages

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#what-youll-learn

"client and server services" -> "services and their clients"    i.e. is client code a service? is 'server service' odd sounding? 

https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#try-what-youll-build

On reading "Before you begin, make sure you have all the necessary prerequisites."  I do not think the guide has listed any at this point? Do you mean things like a JDK, MVN etc?   Agh - I see these listed on the RHS - but missed them initially.

When I issue `mvn -pl system liberty:run` I see the copying of server.xml twice which looks a bit naff:

```
**[INFO] Copying 1 file to /Users/hutchig/git/draft-guide-grpc-intro/finish/system/target/liberty/wlp/usr/servers/defaultServer
[INFO] CWWKM2144I: Update server configuration file server.xml from /Users/hutchig/git/draft-guide-grpc-intro/finish**/system/src/main/liberty/config/server.xml.
[INFO] CWWKM2185I: The liberty-maven-plugin configuration parameter "appsDirectory" value defaults to "apps".
[INFO] CWWKM2160I: Installing application guide-grpc-intro-system.war.xml.
**[INFO] Copying 1 file to /Users/hutchig/git/draft-guide-grpc-intro/finish/system/target/liberty/wlp/usr/servers/defaultServer
[INFO] CWWKM2144I: Update server configuration file server.xml from /Users/hutchig/git/draft-guide-grpc-intro/finish**/system/src/main/liberty/config/server.xml.

```

Also:

```
[INFO] [WARNING ] SRVE0190E: File not found: /favicon.ico
```
Appears every time ` http://localhost:9080/` is hit, it also appears each time
http://localhost:9081/query/properties/os.name is hit on a new browser.

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#implementing-server-streaming-call

Should '.getPropertyName' be better called getPropertyPrefix ?

[EDIT - Sorry this was unclear what it applied to - I suggest:
getProperty( Name  )
getProperties( Prefix ) 

Then, call the getPropertiesServer() -> Then, calls the getPropertiesServer()  (i.e. if you are using creates with an s at the end I think you should be consistent and used calls with an s on the end too.   Same problem with "shutdown the channel and returns"  ....mixed form of expression instructions or descriptions of what needs doing or is being done?

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#implementing-client-streaming-call

"to implement of" -> "to implement"  
I was confused by the word 'placeholder' being used to describe what is being sent back to the client.

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#implementing-client-streaming-call

"properties started with user." -> "properties with property names prefixed by 'user.' "

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#implementing-bidirectional-streaming-call

"returns an instance"  and "close the server" so the same mix of description and instruction forms of words  when both bits of function have the same initial location (provided/not provided in skeleton file or RHS etc.) or perhaps I am missing something?

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#running-the-tests

It would useful to identify WHICH session one can press return in (as there are multiple session in dev mode
at this point) query.

Overall I thought it was very clear (well as can be expected for gRPC!) thank you for doing such a good job.

**Comment by gkwan-ibm** [comment] 2022-09-06 16:12
Regarding
> When I issue mvn -pl system liberty:run I see the copying of server.xml twice which looks a bit naff:

I opened https://github.com/OpenLiberty/ci.maven/issues/1584

**Comment by gkwan-ibm** [comment] 2022-09-06 17:15
Regarding
> `[INFO] [WARNING ] SRVE0190E: File not found: /favicon.ico`

It was caused by the browser request (not from the api or OL internal). I don't think we should hide it by either 
- add an icon file to the src or 
- add `<logging hideMessage="SRVE0190E"/>` to the server.xml.

**Comment by shin19991207** [comment] 2022-09-06 18:31
Addressed in https://github.com/OpenLiberty/draft-guide-grpc-intro/pull/11

**Closed as completed** 2022-09-16 03:49 UTC
